version: '3'
services:
  # pong-front:

  pong-backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend/:/backend/:cached
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - front_back
      - back_db

  pong-db:
    image: postgres:alpine
    container_name: db
    env_file:
      - .env
    networks:
      - back_db
    volumes:
      - ${PRIVATE_PATH_DB}:/var/lib/postgresql/data/:cached

  pong-dev:
    image: dpage/pgadmin4
    profiles:
      - dev
    container_name: dev
    volumes:
      - ${PRIVATE_PATH_DEV}:/var/lib/pgadmin:cached
    ports:
      - "5050:80"
    env_file:
      - .env
    networks:
      - back_db

networks:
  front_back:
  back_db:
